[package]
name = "scratch-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
scratch-blocks = { path = "../scratch-blocks" }
scratch-ir = { path = "../scratch-ir" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
scratch-language = { path = "../scratch-language" }
